name: Update publications from ORCID

on:
  schedule:
    - cron: "0 0 * * 0"   # weekly
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch ORCID publications
        run: |
          curl -s "https://pub.orcid.org/v3.0/0000-0002-0615-9587/works" \
          -H "Accept: application/json" \
          | python scripts/orcid_to_yaml.py

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add _data/publications.yml
          git commit -m "Auto-update publications" || echo "No changes"
          git push
